language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

install:
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=tools
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=build-tools-25.0.2
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=android-25
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=extra-android-m2repository
  - android-update-sdk --accept-licenses='android-sdk-license-.+' --components=extra-google-m2repository
